dist: xenial
language: python
python:
  - 3.8

before_install:
  - pip install poetry
install:
  - poetry install

before_script:
  - cp .env-sample .env

script:
  - poetry run pyupgrade --py38-plus $(find . -name '*.py')
  - poetry run isort --check-only
  - poetry run black . --check
  - poetry run ./manage.py makemigrations --check  # validate no outstanding model changes
  - poetry run coverage run ./manage.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
