[tool.poetry]
name = "rooster"
version = "0.1.0"
description = "A tool to review activity on GitHub for daily standup."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.2"
django-configurations = "^2.2"
social-auth-app-django = "^3.1"
PyGithub = "^1.45"
zappa = "^0.48.2"
django-s3-sqlite = "^0.0.2"
django-s3-storage = "^0.13.0"
django-tz-detect = "^0.3.0"
jira = "^2.0"
django-cryptography = "^0.3.0"

[tool.poetry.dev-dependencies]
black = {version = "^19.10b0", allows-prereleases = true}
pyupgrade = "^1.25"
coverage = "^5.0"
factory-boy = "^2.12"

[tool.black]
line-length = 88
target_version = ["py36"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
