[tool.poetry]
name = "rooster"
version = "0.1.0"
description = "A tool to review activity on GitHub for daily standup."
authors = ["Lucas Connors <lucas@revolutiontech.ca>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.6"
Django = "~2.2"
django-configurations = "^2.1"
social-auth-app-django = "^3.1"
PyGithub = "^1.44"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allows-prereleases = true}
pyupgrade = "^1.25"
factory-boy = "^2.12"

[tool.black]
line-length = 88
target_version = ["py36"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
