# Generated by Django 2.2.8 on 2020-01-20 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jira_server_url",
                    models.URLField(blank=True, verbose_name="JIRA Server URL"),
                ),
                (
                    "jira_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="JIRA Email"
                    ),
                ),
                (
                    "jira_api_key",
                    django_cryptography.fields.encrypt(
                        models.CharField(
                            blank=True, max_length=24, verbose_name="JIRA API Key"
                        )
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
